### ISSUE TITLE
in: No "version" file created

### ISSUE THREAD

**Issue by drnic** [aequitas/concourse-ftp-resource#13]
I have a resource below and when I `get` it I don't see a `version` file.

```yaml
  - name: freetds
    type: ftp
    source:
      uri: ftp://ftp.freetds.org/pub/freetds/stable/
      regex: (?P<file>freetds-(?P<version>[1-9][0-9]*\.[1-9][0-9]*\.[0-9]+).*.tar.gz)
```

Files created by the resource:

```
ll freetds/
total 3044
drwxr-xr-x 1 root root      40 Jun  8 11:19 ./
drwxr-xr-x 1 root root      32 Jun  8 11:34 ../
-rw-r--r-- 1 root root 3115440 Jun  8 11:19 freetds-1.1.6.tar.gz
```

Should I get a `version` file with `1.1.6` in it? If not, could we have this please?

I also got the feeling from the README that I'd get a `file` file with `freetds-1.1.6.tar.gz` in it. Is this a misreading too?
